
size = [5, 5]

rods = [
    [ 50, 75, 75, 75, 10 ],
    [ 75, 75, 60, 75, 75 ],
    [ 75, 100, 75, 75, 75 ],
    [ 75, 75, 75, 75, 75 ],
    [ 88, 75, 0, 75, 99 ],
]

zones = [ # for now, maximum is 5000
    [ "skip", 0, 3000, "skip" ],
    [ 5000, 200, 200, 500 ],
    [ 200, 1500, 10, 200 ],
    [ "skip", 5000, 2, "skip" ],
]

water_temp = 90.0

water_pressure = 25.0