
size = [5, 5]

rods = [
    [ 75, 75, 75, 75, 75 ],
    [ 75, 75, 75, 75, 75 ],
    [ 75, 75, 75, 75, 75 ],
    [ 75, 75, 75, 75, 75 ],
    [ 75, 75, 75, 75, 75 ],
]

zones = [ # for now, maximum is 5000
    [ 0, 3000, ],
    [ 5000, 200, 200, 500 ],
    [ 200, 1500, 10, 200 ],
    [ 5000, 2, ],
]

water_temp = 90.0

water_pressure = 25.0